### ISSUE TITLE
Choose HTML templates

### ISSUE THREAD

**Issue by atais** [funilrys/gentelella#16]
So as I have mentioned in #3 I think we should rewrite the HTML as well.

It will give us more control over this messy code and minimize the repetitions.

For the beginning it would be enough to partition the existing HTML, later we could make some changes. For example, I could adapt #3 to it.

I can create the workflow but I want your opinion on the engine we will choose, there is a nice website:
https://garann.github.io/template-chooser/

Get familiar with those projects.

My best picks are:
- http://handlebarsjs.com/
- http://mustache.github.io/

but you can check the others too and give your opinion.

I think we do not need any logic here, simple template to include parts like:
- scripts / styles
- menu
- topnav
- main content

and to close it with one "base structure" that is enough.

**Comment by atais** [comment]
I think that the only question that is important from the "chooser" is:

> Do you need to pre-compile templates? 

and it is **YES**

**Comment by funilrys** [comment]
I do prefer http://handlebarsjs.com because of it's simplicity after looking at the documentation. 
In between, you made me discover it so thanks :smile_cat:

**Comment by funilrys** [comment]
Gonna start html review with  http://handlebarsjs.com this afternoon between other work :)

**Comment by atais** [comment]
i am not sure if https://mozilla.github.io/nunjucks/ would not be better here.

But i will also have to dive into it, probably I will create an example on a branch.

**Comment by atais** [comment]
This looks promising - nunjucks https://zellwk.com/blog/nunjucks-with-gulp/

**Comment by funilrys** [comment]
Gonna take a took at it later @atais 😉
