### ISSUE TITLE
Dev sass is completely broken.

### ISSUE THREAD

**Issue by atais** [funilrys/gentelella#22]
Guys wtf.

have you not compiled the scripts at all?!!

run:
```
gulp sass scripts default
```

and see your effect

**Comment by funilrys** [comment]
Not on my computer right now but what is the effect ? 🤔😯

**Comment by atais** [comment]
you have broken the styles completely.

![gentelella alela -](https://cloud.githubusercontent.com/assets/1538192/23717426/19558d42-0434-11e7-9356-5cb3dceaf169.jpg)

**Comment by atais** [comment]
I think we should move to my fork.

I will adapt all the changes - travis, handlebars.

and you will rework the sass with pull requests and regression tests.
this is hopeless - and 60 commits of no use.

**Comment by funilrys** [comment]
What !? On my last merged PR it was working perfectly i tested it ...😨 

Okay gonne bisect this when I'm home ...

**Comment by funilrys** [comment]
I didn't pull since my last message about the HTML so ...
![deepinscreenshot20170308200241](https://cloud.githubusercontent.com/assets/14127285/23719116/566c1a7e-043a-11e7-9cfb-bdda09dc7157.png)

**Comment by atais** [comment]
did you

```
gulp sass scripts default
```

??

because the files in `build` folder have not been updated for a long time.
But if you rebuild the sass - it is broken.

**Comment by funilrys** [comment]
At the time of the screenshot it was with "gulp"

**Comment by funilrys** [comment]
I made a screenshot on every execution

**Comment by atais** [comment]
The script was broken.

Simple `gulp` will not rebuild scripts unless there are changes in the sources **while** you have a dev server working.

So please run `gulp sass scripts default` - it will rebuild the styles and serve the content. And you will see it is broken.

**Comment by funilrys** [comment]
Just saw it gonna try to fix asap ...

**Comment by atais** [comment]
I think we should abandon `dev-sass` and create new branch from `master` from main repo.

I will introduce tests, fix gulp, include travis, mustache and we can start moving the changes again. Currently there is around 60 commits that actually break the template. I think it would be good idea not to have this in history. It is not necessary.

What is your opinion?

**Comment by draecko** [comment]
You do realize by running `gulp sass` you're compiling an unfinished WIP scss file right? Of course it's gonna be broken. `app.scss` contains about 25%-50% of the original material.

**Comment by atais** [comment]
What?
So I thought that while you are partitioning the big file it does not break the entire template.

So you are actually not refactoring but building it from scratch?

**Comment by draecko** [comment]
No we are refactoring, but if you want the compile output to be complete and functional you have to include both `custom.scss` **and** `app.scss` in your gulpfile pipe.

Partitioned scss goes into `app.scss` and get removed from `custom.scss` while we're working on it. You cannot expect gulp to just magically fill in the gaps by just compiling `app.scss`.

**Comment by draecko** [comment]
@atais fixed in c8fdd27

**Comment by atais** [comment]
good to have you back @draecko 

sorry I was not involved and I thought it is already sourced in one file.
