### ISSUE TITLE
Dev under "SASS" branch

### ISSUE THREAD

**Issue by funilrys** [funilrys/gentelella#23]
- Test first
- Test all PR before merge 

#TBC

**Comment by funilrys** [comment]
@atais to avoid overwriting, I just wanted to inform that I'm gonna import all nav-* into _navs.scss (new file)

**Comment by atais** [comment]
please create separate branch.
sorry for force push - i wanted to remove merge commit.

**Comment by funilrys** [comment]
I'm in a private branch for now...
