### ISSUE TITLE
Let's get back to work ...

### ISSUE THREAD

**Issue by funilrys** [funilrys/gentelella#27]
Hello @atais @draecko,

I wasn't satisfied with what we did so I started from the beginning into a new branch

I'm done will importing everything from upstream. We now have to structure the [src/scss](https://github.com/funilrys/gentelella/tree/sass-dev/src/scss) directory so we can be more efficient.

@atais I know you started to write the tests but you can now implement into the repository if you want but I think that the structuration as @draecko started in his branch is a priority before we continue around tests and HTML code splitting.

Cheers,
Nissar

**Comment by atais** [comment]
Hello @funilrys .

Great to hear you have some time and will to redo the template. It is really looking great, but it is a developers' hell ;). However, I will be honest, I do not have time for this project now, especially for development. I am now involved more in backed Scala development and I am not even so much up to date with JS/CSS anymore.

What I can do is I can try to advise as far as my knowledge goes. 
First things first, like we did on the fork - you need to setup some build tool, like gulp and tests, for example with phantom css (js) or similar to check if your template still looks the same. 
I do not know of any other css tests available and I don't think there are any.

After this, add all the libs that you are internally using as dependencies and setup build of SASS/JS to minified sources that one can include and use features of this template.

**Comment by draecko** [comment]
Hey Guys, unfortunately I don't have the time to contribute much anymore, though I think I've come quite far with splitting up the css in scss.

**Comment by funilrys** [comment]
@atais Just finished splitting `*.js` into https://github.com/funilrys/gentelella/tree/sass-dev/src/js can you do a quick review when you have time?

Thanks in advance. 

P.S: Also related to https://github.com/puikinsh/gentelella/issues/406#issuecomment-360045680

**Comment by atais** [comment]
@funilrys wow congratz. 
If you want a proper code review please make a separate branch and a PR and I will try to read through as much as possible. So far, LGTM.

**Comment by funilrys** [comment]
@atais thanks.

Here for you https://github.com/funilrys/gentelella/tree/js-review/src/js

**Comment by atais** [comment]
Which branch should I compare against? master?

**Comment by funilrys** [comment]
As you know our original template is just chaos... 

So I split https://github.com/puikinsh/gentelella/blob/master/build/js/custom.js into that directory ... I don't know how we can compare one file to multiple file :thinking:

**Comment by atais** [comment]
ah. just split no changes.
ok, no problem then.
