### ISSUE TITLE
Remove unused branches

### ISSUE THREAD

**Issue by atais** [funilrys/gentelella#4]
- [x] Development
- [x] Development-Febr
- [x] dev
- [ ] dev-sass
- [ ] master
- [x] revert-299-master

Which are required? 
I guess `dev-sass` only?

**Comment by funilrys** [comment]
you can delete all except `dev-sass` and `master` to keep a track about the official commits/changes!

I currently try to integrate Travis :D

**Comment by atais** [comment]
well we can do the travis thing... but what should it check? 
the tests give wrong output
so it could only check if sass is correct... which is not much.

I have disabled it, because I have added it by accident.

**Comment by atais** [comment]
OK, I have removed mentioned branches

**Comment by draecko** [comment]
Sass is checked when you compile it with gulp, so travis won't add
anything.

**Comment by funilrys** [comment]
We should test the compiled/build file. 
So our travis should

- Build from sass (gulp)
- Test the outputed (custom.min.css) & in the same way the HTML files @atais @draecko

**Comment by atais** [comment]
@funilrys - make a new issue about the travis and I will try to make it work accordingly when I have 5 minutes.
