### ISSUE TITLE
Travis implementation

### ISSUE THREAD

**Issue by funilrys** [funilrys/gentelella#5]
We should test the compiled/build file. 
So our travis should:

- [x] Compile sass (gulp)
- [ ] Test the outputed (custom.min.css) & in the same way the HTML files.

**Comment by atais** [comment]
Well so for the moment it is possible to compile the SASS and check if it does compile or not.

The other one - test the styles, I guess can be only handled with #2.
So basically - we have to postpone it until later

**Comment by atais** [comment]
@funilrys OK i do not edit because we override our work :-)

**Comment by atais** [comment]
The possible part is done.

Now if we want more tests, one would have to remake HTMLs.

**Comment by funilrys** [comment]
I think we have to create an issue about how we can remake HTMLs.
