### ISSUE TITLE
Sass is not compiling in dev-sass

### ISSUE THREAD

**Issue by atais** [funilrys/gentelella#8]
Run `gulp css` in `dev-sass` branch

```javascript

22:41:50] Starting 'css'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: src/scss/_colors.scss
Error: Undefined variable: "$default-dark".
        on line 38 of src/scss/_colors.scss
>>     color: $default-dark;
   -----------^

    at options.error (/Users/michalsiatkowski/Documents/gentelella/node_modules/node-sass/lib/index.js:291:26)
```

**Comment by funilrys** [comment]
@draecko there is no `$default-dark` in variables

**Comment by atais** [comment]
Well - right. So, I think you have missed something during code migration. Or it has never been there 💃

**Comment by funilrys** [comment]
I'm on it...

**Comment by atais** [comment]
looks good :-) make PR

**Comment by funilrys** [comment]
Fixed!
Closing.

**Comment by draecko** [comment]
My work was ahead of what you're using in this repo now, so I don't know where you put it..

**Comment by funilrys** [comment]
@draecko all sass goes here: https://github.com/funilrys/gentelella/tree/dev-sass/src/scss (please work on a branch first then PR)

And the fix: https://github.com/funilrys/gentelella/blob/dev-sass/src/scss/_colors.scss
